# Generated by Django 6.1.1 on 2026-09-13 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'user activities'},
        ),
    ]
