"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.1.1.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-default-key')

DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*']

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'store',

    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.context_processors.cart_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'ecommerce_db'),
        'USER': os.getenv('DB_USER', 'ecommerce_user'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# AI provider selection (FR-6)
AI_PROVIDER = os.getenv('AI_PROVIDER', 'deepseek').lower().strip()

_AI_PROVIDERS = {
    'deepseek':   ('DEEPSEEK',   'https://api.deepseek.com',                                 'deepseek-chat'),
    'gemini':     ('GEMINI',     'https://generativelanguage.googleapis.com/v1beta/openai/', 'gemini-2.0-flash'),
    'openai':     ('OPENAI',     'https://api.openai.com/v1',                                'gpt-4o-mini'),
    'groq':       ('GROQ',       'https://api.groq.com/openai/v1',                           'llama-3.3-70b-versatile'),
    'mistral':    ('MISTRAL',    'https://api.mistral.ai/v1',                                'mistral-small-latest'),
    'together':   ('TOGETHER',   'https://api.together.xyz/v1',                              'meta-llama/Llama-3.3-70B-Instruct-Turbo'),
    'openrouter': ('OPENROUTER', 'https://openrouter.ai/api/v1',                             'openai/gpt-4o-mini'),
    'ollama':     ('OLLAMA',     'http://localhost:11434/v1',                                'llama3.2'),
    'custom':     ('CUSTOM_AI',  '',                                                          ''),
}

if AI_PROVIDER not in _AI_PROVIDERS:
    AI_PROVIDER = 'deepseek'

_prefix, _default_url, _default_model = _AI_PROVIDERS[AI_PROVIDER]
AI_API_KEY = os.getenv(f'{_prefix}_API_KEY', '')
AI_BASE_URL = os.getenv(f'{_prefix}_BASE_URL', _default_url)
AI_MODEL = os.getenv(f'{_prefix}_MODEL', _default_model)
AI_TIMEOUT = int(os.getenv(f'{_prefix}_TIMEOUT', '60' if AI_PROVIDER == 'ollama' else '20'))

# Backward compatibility aliases
DEEPSEEK_API_KEY = os.getenv('DEEPSEEK_API_KEY', '')
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')
RECOMMENDATION_TTL_SECONDS = int(os.getenv('RECOMMENDATION_TTL_SECONDS', '21600'))

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}